apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
  name: policy-certificate
  annotations:
    policy.open-cluster-management.io/standards: NIST-CSF
    policy.open-cluster-management.io/categories: PR.DS DataSecurity
    policy.open-cluster-management.io/controls: PR.DS-2 Data-in-transit
spec:
  remediationAction: inform
  disabled: false
  policy-templates:
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: certificate # cert management expiration
        metadata:
          name: policy-certificate-example
        spec:
          namespaceSelector:
            include: ["default"]
            exclude: ["kube-*"]
          remediationAction: inform # will be overridden by remediationAction in parent policy
          severity: low
          minimumDuration: 300h
---
apiVersion: policy.open-cluster-management.io/v1
kind: PlacementBinding
metadata:
  name: binding-policy-certificate
placementRef:
  name: placement-policy-certificate
  kind: PlacementRule
  apiGroup: apps.open-cluster-management.io
subjects:
- name: policy-certificate
  kind: Policy
  apiGroup: policy.open-cluster-management.io
---
apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  name: placement-policy-certificate
spec:
  clusterConditions:
  - type: OK
  clusterSelector:
    matchExpressions:
      []
